#
# Copyright IBM Corporation 2020
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   IBM Corporation - implementation
#

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: wazi-codeready-operator-catalog
  namespace: openshift-marketplace
  labels:
    name: wazi-codeready-operator-catalog
    app.kubernetes.io/name: wazi-codeready-operator-catalog
    app.kubernetes.io/instance: wazi-codeready-operator-catalog-1.1.0
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/component: workspaces
    app.kubernetes.io/part-of: wazi-developer
    app.kubernetes.io/managed-by: olm
  annotations:
    productID: "9d41d2d8126f4200b62ba1acc0dffa2e"
    productName: "IBM Wazi Developer for Red Hat CodeReady Workspaces"
    productMetric: "VIRTUAL_PROCESSOR_CORE"
    productChargedContainers: "All"
    productVersion: "1.1.0"
            
spec:
  sourceType: grpc
  displayName: IBM Wazi Developer Operators
  publisher: IBM
  image: docker.io/ibmcom/wazi-code-operator-catalog@sha256:a436db8522674ac9dbd6b46188a2ceb03370a0a7987d5658a8ff383d7bce0bfe
  # tag: docker.io/ibmcom/wazi-code-operator-catalog:1.1.0
