#
# Copyright IBM Corporation 2021
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   IBM Corporation - implementation
#

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: wazi-codeready-operator-catalog
  namespace: openshift-marketplace
  labels:
    name: wazi-codeready-operator-catalog
    app.kubernetes.io/name: wazi-codeready-operator-catalog
    app.kubernetes.io/instance: wazi-codeready-operator-catalog-1.4.0
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/component: workspaces
    app.kubernetes.io/part-of: wazi-developer
    app.kubernetes.io/managed-by: olm
  annotations:
    productVersion: "1.4.0"
            
spec:
  sourceType: grpc
  displayName: IBM Wazi Developer Operators
  publisher: IBM
  image: icr.io/cpopen/ibm-wazi-developer-for-workspaces-catalog@sha256:d7f26aa2f05fdc9812d5347f1f36eb1d5d3d77467ff34982e4d08fe89375b036
  # tag: icr.io/cpopen/ibm-wazi-developer-for-workspaces-catalog:1.4.0
