#
# Copyright IBM Corporation 2020
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   IBM Corporation - implementation
#

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: wazi-codeready-operator-catalog
  namespace: openshift-marketplace
  labels:
    name: wazi-codeready-operator-catalog
    app.kubernetes.io/name: wazi-codeready-operator-catalog
    app.kubernetes.io/instance: wazi-codeready-operator-catalog-1.0.0
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: workspaces
    app.kubernetes.io/part-of: wazi-developer
    app.kubernetes.io/managed-by: operator
  annotations:
    productID: "9d41d2d8126f4200b62ba1acc0dffa2e"
    productName: "IBM Wazi Development Client for Red Hat CodeReady Workspaces"
    productMetric: "VIRTUAL_PROCESSOR_CORE"
    productChargedContainers: "All"
    productVersion: "1.0.0"
            
spec:
  sourceType: grpc
  displayName: IBM Wazi Developer Operators
  publisher: IBM
  image: docker.io/ibmcom/wazi-code-operator-catalog@sha256:fc3daea5c8043a9db4e6ec78f6d09f1e8fa245d3bc78f9138ac7de307c8a5ecc
  # tag: docker.io/ibmcom/wazi-code-operator-catalog:1.0.0
