language: minimal
sudo: required
dist: trusty
group: bluezone
services:
- docker
env:
  global:
  - IMAGE="docker.io/ibmcom/wazi-code-operator-catalog"
# docker build -t ${IMAGE}:travis .
install: docker version
script: echo "Success!"
notifications:
  slack: ibm-systems-z:kiD2FZtJUJtUSp57dwHWwNX1
