apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wazi-codeready-workspaces-metrics-exporter
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - wazi-codeready-workspaces
  selector:
    matchLabels:
      app.kubernetes.io/component: codeready
