apiVersion: scorecard.operatorframework.io/v1alpha3
kind: Configuration
metadata:
  name: config
  labels:
    app.kubernetes.io/name: che
    app.kubernetes.io/instance: che
    app.kubernetes.io/managed-by: olm
stages:
  - parallel: true
    tests:
      - image: quay.io/operator-framework/scorecard-test:latest
        entrypoint:
          - scorecard-test
          - basic-check-spec
        labels:
          suite: basic
          test: basic-check-spec-test
      - image: quay.io/operator-framework/scorecard-test:latest
        entrypoint:
          - scorecard-test
          - olm-bundle-validation
        labels:
          suite: olm
          test: olm-bundle-validation-test
      - image: quay.io/operator-framework/scorecard-test:latest
        entrypoint:
          - scorecard-test
          - olm-crds-have-validation
        labels:
          suite: olm
          test: olm-crds-have-validation-test
      - image: quay.io/operator-framework/scorecard-test:latest
        entrypoint:
          - scorecard-test
          - olm-status-descriptors
        labels:
          suite: olm
          test: olm-status-descriptors-test
