#
#  Copyright (c) 2018-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeready-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: codeready-operator
  template:
    metadata:
      labels:
        name: codeready-operator
    spec:
      serviceAccountName: codeready-operator
      containers:
        - name: codeready-operator
          image: registry.redhat.io/codeready-workspaces/crw-2-rhel8-operator:latest
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - codeready-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: codeready-operator
            - name: CHE_VERSION
              value: 2.3.0
            - name: RELATED_IMAGE_che_server
              value: registry.redhat.io/codeready-workspaces/server-rhel8:2.3
            - name: RELATED_IMAGE_plugin_registry
              value: registry.redhat.io/codeready-workspaces/pluginregistry-rhel8:2.3
            - name: RELATED_IMAGE_devfile_registry
              value: registry.redhat.io/codeready-workspaces/devfileregistry-rhel8:2.3
            - name: RELATED_IMAGE_pvc_jobs
              value: registry.access.redhat.com/ubi8-minimal:8.2
            - name: RELATED_IMAGE_postgres
              value: registry.redhat.io/rhel8/postgresql-96:1
            - name: RELATED_IMAGE_keycloak
              value: registry.redhat.io/rh-sso-7/sso74-openshift-rhel8:7.4
            - name: RELATED_IMAGE_che_workspace_plugin_broker_metadata
              value: registry.redhat.io/codeready-workspaces/pluginbroker-metadata-rhel8:2.3
            - name: RELATED_IMAGE_che_workspace_plugin_broker_artifacts
              value: registry.redhat.io/codeready-workspaces/pluginbroker-artifacts-rhel8:2.3
            - name: RELATED_IMAGE_che_server_secure_exposer_jwt_proxy_image
              value: registry.redhat.io/codeready-workspaces/jwtproxy-rhel8:2.3
            - name: CHE_FLAVOR
              value: codeready
            - name: CONSOLE_LINK_NAME
              value: che
            - name: CONSOLE_LINK_DISPLAY_NAME
              value: CodeReady Workspaces
            - name: CONSOLE_LINK_SECTION
              value: Red Hat Applications
            - name: CONSOLE_LINK_IMAGE
              value: /dashboard/assets/branding/loader.svg
            - name: CHE_IDENTITY_SECRET
              value: che-identity-secret
            - name: CHE_IDENTITY_POSTGRES_SECRET
              value: che-identity-postgres-secret
            - name: CHE_POSTGRES_SECRET
              value: che-postgres-secret
            - name: CHE_SERVER_TRUST_STORE_CONFIGMAP_NAME
              value: ca-certs
